### PR TITLE
Move blog/news to index page

### PR DESCRIPTION
**Pull request by mjaehn**
On our page, we have a nice blog feature where we announce workshops, updates about the website, the Alps transition and so on. However, it is not visible at first sight since the starting page is the info about the C2SM Core Team.

With this PR I suggest to have the News on the starting page. Feedback is very welcome 🙂

### CODE REVIEW

**Review by AnnikaLau — DISMISSED** [review]
LGTM, I just have one suggestion/idea on top of it:
We could make the news entries collapsibles. That would give a better overview over the latest news and you can just click on what is of interest for you. What do you think?

**Comment by mjaehn** [comment]
Thanks @AnnikaLau!

I don't know if it is possible to make the posts collapsible. At least I didn't find such a settings.

What we can do however is to add `<!-- more -->` to all posts (most of them have it already) so that only the first paragraph of each post is visible on the home page.

Otherwise, there is already an overview of all posts on the right sidebar, and on the left by clicking on "Posts".

**Review by jonasjucker — APPROVED** [review]

**Comment by jonasjucker** [comment]
one question:
Will the link I posted recently for IUW still be valid?

**Comment by mjaehn** [comment]
> one question: Will the link I posted recently for IUW still be valid?

Did you reference to the news post? In your email, there is only this (which is still valid): https://c2sm.github.io/events/CIUW/2024/

**Comment by mjaehn** [comment]
@jonasjucker If you have posted the news link already, you have to replace it after the merge. New link:
https://c2sm.github.io/2024-11-26-icon-user-workshop-formerly-cosmo-icon-user-workshop/

**Pull request merged**
